main: mightiness.Main
name: Mightiness
version: 1.0.0
author: UnlimitedGamesNetwork
description: Made by PublicGameCoder & MennoGamed.
api-version: 1.15

commands:
   mightiness:
      description: The Mightiness main command!
      usage: "Unknown command. Type \"/help\" for help."
      aliases: [min, help, info]